name: Release

on:
  push:
    branches:
      - main
      - beta

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: jabrown93/.github/.github/workflows/docker-release.yml@318fa3ed5ddce0cc6bd43e230b5ccd1972fa093c # v1.3.0
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      image: ghcr.io/jabrown93/artwork-uploader
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
